a = "DIQMTQSPSTLSASVGDRVTITCRASQSISRWLAWYQQKPGKVPKLLIYKASSLESGVPSRFSGSGSGTEFTLTISSLQMDDFATYYCQQYNSYSFGPGTKVDIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
b = "DIQMTQSPSTLSASVGDRVTITCRASQSISRWLAWYQQKPGKVPKLLIYKASSLESGVPSRFSGSGSGTEFTLTISSLQPDDFATYYCQQYNSYSFGPGTKVDIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC"
for i in range(len(a)):
    if a[i] != b[i]:
        print(a[i])
        print(i)
