[uwsgi]
socket = 127.0.0.1:9098
chdir = /Users/danfeng/falcon2/web
home = /Users/danfeng/miniconda3/envs/falcon2
manage-script-name = 1
mount = app:app
processes = 1
daemonize = uwsgi.log
threads = 1
buffer-size = 32768
master = true
stats = uwsgi.status
pidfile = uwsgi.pid
touch-reload = 1
